spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bitsplus?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qc123


#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/bitsplus?useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: qc123
#    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true  #开启驼峰命名